export default function Terms() {
  return (
    <div
      style={{
        maxWidth: "900px",
        margin: "0 auto",
        padding: "40px 20px",
        fontFamily: "Georgia, serif",
        lineHeight: "1.8",
        color: "#333",
      }}
    >
      <h1 style={{ color: "#d97706", marginBottom: "30px" }}>
        Terms of Service
      </h1>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using PageWise, you agree to these Terms of Service.
        If you do not agree with these terms, please do not use the service.
      </p>

      <h2>2. About PageWise</h2>
      <p>
        PageWise is an AI-powered document analysis platform operated by
        Saevora. The service allows users to upload documents, ask questions,
        generate summaries, create study materials, and receive AI-assisted
        insights.
      </p>

      <h2>3. User Responsibilities</h2>
      <ul>
        <li>You are responsible for the documents and content you upload.</li>
        <li>
          You must have the right to upload and analyze any document you
          provide.
        </li>
        <li>You must comply with all applicable laws and regulations.</li>
        <li>
          You must not upload unlawful, harmful, malicious, or infringing
          content.
        </li>
        <li>
          You understand that AI-generated responses may contain inaccuracies.
        </li>
      </ul>

      <h2>4. AI-Generated Content Disclaimer</h2>
      <p>
        PageWise uses artificial intelligence to generate responses and
        insights. AI-generated content may contain inaccuracies, omissions,
        or outdated information. Users are responsible for independently
        verifying important information before relying on it.
      </p>

      <h2>5. Medical and Legal Disclaimer</h2>

      <p>
        <strong>Medical Information:</strong> PageWise is not a substitute
        for professional medical advice, diagnosis, or treatment. Always
        consult qualified healthcare professionals regarding medical
        decisions.
      </p>

      <p>
        <strong>Legal Information:</strong> PageWise is not a substitute
        for professional legal advice. Always consult a licensed attorney
        regarding legal matters.
      </p>

      <h2>6. Paid Subscriptions</h2>

      <p>
        PageWise may offer paid subscription plans and premium features.
      </p>

      <p>
        Subscription pricing, features, and limits are displayed within
        the application and may change over time.
      </p>

      <p>
        Subscriptions may automatically renew unless cancelled in accordance
        with the applicable billing terms.
      </p>

      <h2>7. Intellectual Property</h2>

      <p>
        The PageWise platform, software, branding, trademarks, and related
        materials are owned by Saevora.
      </p>

      <p>
        Users retain ownership of documents and content they upload.
      </p>

      <h2>8. Limitation of Liability</h2>

      <p>
        PageWise is provided on an &quot;as is&quot; and &quot;as available&quot;
        basis.
      </p>

      <p>
        To the fullest extent permitted by law, Saevora shall not be liable
        for:
      </p>

      <ul>
        <li>Errors or inaccuracies in AI-generated responses</li>
        <li>Service interruptions or downtime</li>
        <li>Loss of data</li>
        <li>Decisions made based on information generated by the service</li>
        <li>Indirect, incidental, or consequential damages</li>
      </ul>

      <h2>9. Changes to the Service</h2>

      <p>
        We may modify, suspend, or discontinue features of the service at
        any time. We may also update these Terms from time to time.
      </p>

      <h2>10. Contact</h2>

      <p>
        Questions regarding these Terms may be directed to:
      </p>

      <p>
        <strong>support@pagewise.app</strong>
      </p>

      <p
        style={{
          marginTop: "40px",
          fontSize: "12px",
          color: "#666",
        }}
      >
        Last Updated: June 2026
      </p>
    </div>
  );
}